In [1]:
import pandas as pd
iw=pd.DataFrame({"city":["Kurnool","Anantapur","Hyderabad"],
                 "temparature":[38,40,30],
                 "humidity":[10,11,9]})
iw

        city  temparature  humidity
0    Kurnool           38        10
1  Anantapur           40        11
2  Hyderabad           30         9

In [2]:
w=pd.DataFrame({"city":["Darjeeling","Manali","Meghalaya"],
                 "temparature":[18,15,20],
                 "humidity":[0,1,9]})
w

         city  temparature  humidity
0  Darjeeling           18         0
1      Manali           15         1
2   Meghalaya           20         9

In [3]:
df=pd.concat([iw,w])
df

         city  temparature  humidity
0     Kurnool           38        10
1   Anantapur           40        11
2   Hyderabad           30         9
0  Darjeeling           18         0
1      Manali           15         1
2   Meghalaya           20         9

In [4]:
#if we observe the index of df then we can see 0,1,2 and its repeating, we don't want it to happen in that wayy
df=pd.concat([iw,w],ignore_index=True)
df

         city  temparature  humidity
0     Kurnool           38        10
1   Anantapur           40        11
2   Hyderabad           30         9
3  Darjeeling           18         0
4      Manali           15         1
5   Meghalaya           20         9

In [6]:
df=pd.concat([iw,w],keys=["fav visited places","fav to be visited places"])
df

                                  city  temparature  humidity
fav visited places       0     Kurnool           38        10
                         1   Anantapur           40        11
                         2   Hyderabad           30         9
fav to be visited places 0  Darjeeling           18         0
                         1      Manali           15         1
                         2   Meghalaya           20         9

In [9]:
#the above , we have divided the combined table as fav visited places, fav to be visited places, to find the subsets of each , we can do as:
df.loc['fav visited places']
df.loc['fav to be visited places']

         city  temparature  humidity
0  Darjeeling           18         0
1      Manali           15         1
2   Meghalaya           20         9

In [5]:
tdf={"city":["Kurnool","Anantapur","Hyderabad"],
                 "temparature":[38,40,30],
                 }
tdf
#ttdf=pd.DataFrame({"city":["Kurnool","Anantapur","Hyderabad"],
  #               "temparature":[38,40,30],
 #                "humidity":[10,11,9]})
#ttdf
tsf={"city":["Kurnool","Anantapur","Hyderabad"],
                 "humidity":[10,11,9]}
tsf

{'city': ['Kurnool', 'Anantapur', 'Hyderabad'], 'humidity': [10, 11, 9]}

In [10]:
#in pd.concat([we need to pass only dataframes where tdf,tsf are still dictionaries if we passs then we get an error])
#df=pd.concat([tdf,tsf])
ttdf=pd.DataFrame(tdf)
tssf=pd.DataFrame(tsf)
df=pd.concat([ttdf,tssf],ignore_index=True)
df
#now wew can see the df has appended ttdf,tssf rows even they though they have same rows and one different column , what i want to see is whenever we have such dataframes where it has atleast one complete column same and differnet columns have different values then we can have the another column , that we can do as
ddf=pd.concat([ttdf,tssf],axis=1)
ddf

        city  temparature       city  humidity
0    Kurnool           38    Kurnool        10
1  Anantapur           40  Anantapur        11
2  Hyderabad           30  Hyderabad         9

In [15]:
#now here in the above dataframes ttdf,tssf the cities are in same order but what if we don't have them in same order
r={"city":["Darjeeling","Manali","Meghalaya"],
                 "ttt":[38,40,30],
                 }
s={"city":["Manali","Darjeeling"],
                 "humidity":[10,11]}
rdf=pd.DataFrame(r)
sdf=pd.DataFrame(s)
df=pd.concat([rdf,sdf],axis=1)
df
#here df is wrong where in oth index we have Darjeeling and manali where both are 2 differnet cities and on city's data is missing here , so its giving wrong data op , so what we can do is 
rsdf=pd.DataFrame(r,index=[0,1,2])
ssdf=pd.DataFrame(s,index=[1,0])
ddf=pd.concat([rsdf,ssdf],axis=1)
ddf

         city  ttt        city  humidity
0  Darjeeling   38  Darjeeling      11.0
1      Manali   40      Manali      10.0
2   Meghalaya   30         NaN       NaN

In [ ]:
#If both DataFrames have the same column like "city", and you want only one copy:
#df = pd.concat([tdf.set_index("city"), tsf.set_index("city")], axis=1).reset_index()
#print(df)
#Output:
 #       city  temperature  humidity
#0    Kurnool           38        10
#1  Anantapur           40        11
#2  Hyderabad           30         9
#So remember:
#✔ Convert dict → DataFrame first
#✔ Use axis=1 to combine column-wise or axis=0 to stack row-wise



#Option 1: Merge on the “city” column (recommended)
#When you want to join based on matching city names:
#df = pd.merge(rdf, sdf, on="city", how="outer")
#print(df)
#✅ Output:
 #       city  ttt  humidity
#0  Darjeeling   38      11.0
#1       Manali   40      10.0
#2    Meghalaya   30       NaN
#Here:
#Rows are matched based on "city".
#how="outer" keeps all cities (even if missing in one DataFrame).
#Missing values are filled with NaN.
#You can replace NaN if you like:
#df = df.fillna(0)




#Option 2: Set “city” as index and concatenate
#rdf = rdf.set_index("city")
#sdf = sdf.set_index("city")
#df = pd.concat([rdf, sdf], axis=1)
#print(df.reset_index())
#✅ Output:
 #       city  ttt  humidity
#0  Darjeeling   38      11.0
#1       Manali   40      10.0
#2    Meghalaya   30       NaN
#Here, the concatenation is now aligned by city names (index), not just row positions.



#Goal	Method
#Match rows by order	pd.concat([...], axis=1)
#Match rows by a column value (like “city”)	pd.merge(..., on="city")
#Match rows by index	set_index() + pd.concat(..., axis=1)