In [1]:
#DataFrames is a main object in pandas,it is used to represent data with rows and columns
import pandas as pd
#now we have some dataset in some location , to convert the dataset into dataframe we do the below operation ".read_csv("and mention the path , remember in py if the path contains \ it treats as escape sequence , so to avoid that we say r"and mention the entire path"
df=pd.read_csv(r"D:\UPSKILL 2025\Python Packages\bwf_historic_rankings.csv",low_memory=False)
df

,Unnamed: 0,rank,delta_rank,country_code,name,id,points,tournaments_played,continent,country,date,draw
0,0,1,0.0,DEN,VIKTOR AXELSEN,25831,107455,15.0,Europe,Denmark,24-10-2023,MS
1,1,2,0.0,INA,ANTHONY SINISUKA GINTING,95661,86611,19.0,Asia,Indonesia,24-10-2023,MS
2,2,3,0.0,JPN,KODAI NARAOKA,62063,82015,23.0,Asia,Japan,24-10-2023,MS
3,3,4,1.0,THA,KUNLAVUT VITIDSARN,64032,79778,18.0,Asia,Thailand,24-10-2023,MS
4,4,5,1.0,CHN,LI SHI FENG,95476,78548,23.0,Asia,China,24-10-2023,MS
...,...,...,...,...,...,...,...,...,...,...,...,...
888495,888595,96,NaN,NaN,MILES N C JOHNSON / SUZANNE LOUIS-LANE,NaN,4920,NaN,NaN,ENGLAND,01-01-1990,XD
888496,888596,97,NaN,NaN,PETER ROBERTS / LISA CAMPBELL,NaN,4900,NaN,NaN,AUSTRALIA,01-01-1990,XD
888497,888597,98,NaN,NaN,ZHANG QIANG / SHI WEN,NaN,4900,NaN,NaN,CHINA,01-01-1990,XD
888498,888598,99,NaN,NaN,PETER BLACKBURN / GILLIAN SANDERSON,NaN,4900,NaN,NaN,AUSTRALIA,01-01-1990,XD
888499,888599,100,NaN,NaN,LEE KWANG JIN / GIL YOUNG AH,NaN,4880,NaN,NaN,KOREA,01-01-1990,XD

In [5]:
#when we have our data in dictionary format,but wanna convert it to dataframe then:
d={'name':["jaihanuman","rajasri","rakshitha","vasavi","badminton"],'type':["god","hb","hb","hb","sport"]}
dff=pd.DataFrame(d)
dff
#df.shape() returns a tuple which contains the number of rows and columns
dff.shape
#When you write df.shape(),
#Python thinks you’re trying to call a function named shape.
#But actually, df.shape returns a tuple, like (5, 2).
#And when you add (), you’re trying to “call” that tuple — which is not callable.
#Hence the error:
#TypeError: 'tuple' object is not callable
#It literally means:
#“You’re trying to use parentheses on something that’s not a function.”
#🧠 Quick analogy
#You want	Correct	Wrong
#Get the number of rows and columns	df.shape	df.shape()
#Get column names	df.columns	df.columns()
#But if it’s a method (function), like viewing top rows	✅ df.head()	❌ df.head

(5, 2)

In [6]:
#df.head(n) which gives top rows and columns from dataset,it is useful when the entire dataset is very large,here we can specify no of rows and columns we want to see that is "n"
dff.head()

         name   type
0  jaihanuman    god
1     rajasri     hb
2   rakshitha     hb
3      vasavi     hb
4   badminton  sport

In [7]:
#df.tail(n) which gives last rows and columns from dataset,it is useful when the entire dataset is very large,here we can specify no of rows and columns we want to see that is "n"
dff.tail(2)

        name   type
3     vasavi     hb
4  badminton  sport

In [3]:
#we can do indexing in dataframes too, which includes 2,3,4th row 
df[2:5]
#df[:] prints the entire dataframe object , just like df does

,Unnamed: 0,rank,delta_rank,country_code,name,id,points,tournaments_played,continent,country,date,draw
2,2,3,0.0,JPN,KODAI NARAOKA,62063,82015,23.0,Asia,Japan,24-10-2023,MS
3,3,4,1.0,THA,KUNLAVUT VITIDSARN,64032,79778,18.0,Asia,Thailand,24-10-2023,MS
4,4,5,1.0,CHN,LI SHI FENG,95476,78548,23.0,Asia,China,24-10-2023,MS

In [10]:
#to print the column names
df.columns
#sometimes we need to print the single column content , we can do it as "df.columnname" or df['columnname']
df.name
df['points']

0         107455
1          86611
2          82015
3          79778
4          78548
           ...
888495      4920
888496      4900
888497      4900
888498      4900
888499      4880
Name: points, Length: 888500, dtype: int64

In [11]:
#to know the type of the column , type(dataframename['columnname']) which is always pandas.series
type(df['id'])

pandas.core.series.Series

In [3]:
#to print 2 columns 
df[['name','id']]

                                          name     id
0                               VIKTOR AXELSEN  25831
1                     ANTHONY SINISUKA GINTING  95661
2                                KODAI NARAOKA  62063
3                           KUNLAVUT VITIDSARN  64032
4                                  LI SHI FENG  95476
...                                        ...    ...
888495  MILES N C JOHNSON / SUZANNE LOUIS-LANE    NaN
888496           PETER ROBERTS / LISA CAMPBELL    NaN
888497                   ZHANG QIANG / SHI WEN    NaN
888498     PETER BLACKBURN / GILLIAN SANDERSON    NaN
888499            LEE KWANG JIN / GIL YOUNG AH    NaN

[888500 rows x 2 columns]

In [5]:
df['points'].max()
df['points'].min()
df['points'].mean()
df['points'].std()

17418.04139364833

In [6]:
#.describe() helps in giving count,mean,std,min,25,50,75,max of all columns which has integer values , printing the statistical values on data
df.describe()

,Unnamed: 0,rank,delta_rank,points,tournaments_played
count,888500.000000,888500.000000,29000.000000,888500.000000,29000.000000
mean,444349.488745,50.499992,1.470241,24801.090607,15.904379
std,256488.020919,28.866082,3.214421,17418.041394,5.667646
min,0.000000,1.000000,0.000000,3850.000000,2.000000
25%,222224.750000,25.750000,0.000000,12330.000000,11.000000
50%,444349.500000,50.000000,0.000000,19660.000000,16.000000
75%,666474.250000,75.250000,2.000000,31851.000000,20.000000
max,888599.000000,100.000000,130.000000,122606.000000,37.000000

In [8]:
#we can fetch the dataframe rows,columns based on some condition 
#df[df.rank>1.000000] this raises an error bcz in py we have rank(), so when we write .rank without () its treating the column as some error in method, so to avoid this what we can do is 
df[df["rank"]>1.000000]

,Unnamed: 0,rank,delta_rank,country_code,name,id,points,tournaments_played,continent,country,date,draw
1,1,2,0.0,INA,ANTHONY SINISUKA GINTING,95661,86611,19.0,Asia,Indonesia,24-10-2023,MS
2,2,3,0.0,JPN,KODAI NARAOKA,62063,82015,23.0,Asia,Japan,24-10-2023,MS
3,3,4,1.0,THA,KUNLAVUT VITIDSARN,64032,79778,18.0,Asia,Thailand,24-10-2023,MS
4,4,5,1.0,CHN,LI SHI FENG,95476,78548,23.0,Asia,China,24-10-2023,MS
5,5,6,1.0,INA,JONATAN CHRISTIE,73442,76921,18.0,Asia,Indonesia,24-10-2023,MS
...,...,...,...,...,...,...,...,...,...,...,...,...
888495,888595,96,NaN,NaN,MILES N C JOHNSON / SUZANNE LOUIS-LANE,NaN,4920,NaN,NaN,ENGLAND,01-01-1990,XD
888496,888596,97,NaN,NaN,PETER ROBERTS / LISA CAMPBELL,NaN,4900,NaN,NaN,AUSTRALIA,01-01-1990,XD
888497,888597,98,NaN,NaN,ZHANG QIANG / SHI WEN,NaN,4900,NaN,NaN,CHINA,01-01-1990,XD
888498,888598,99,NaN,NaN,PETER BLACKBURN / GILLIAN SANDERSON,NaN,4900,NaN,NaN,AUSTRALIA,01-01-1990,XD
888499,888599,100,NaN,NaN,LEE KWANG JIN / GIL YOUNG AH,NaN,4880,NaN,NaN,KOREA,01-01-1990,XD

In [9]:
#when we want to retrieve the row whose rank is max then we can do is df[df.column name==df.column name.max()]
df[df["rank"]==df["rank"].max()]

,Unnamed: 0,rank,delta_rank,country_code,name,id,points,tournaments_played,continent,country,date,draw
99,99,100,3.0,TPE,KUO KUAN LIN,59077,16050,17.0,Asia,Chinese Taipei,24-10-2023,MS
199,299,100,2.0,TPE,WANG PO-WEI,87029,16690,10.0,Asia,Chinese Taipei,31-10-2023,MS
299,399,100,6.0,AUT,COLLINS VALENTINE FILIMON,86887,17510,11.0,Europe,Austria,07-11-2023,MS
399,499,100,2.0,VIE,NGUYEN HAI DANG,64648,17270,18.0,Asia,Vietnam,14-11-2023,MS
499,599,100,10.0,INA,CHRISTIAN ADINATA,69006,16890,5.0,Asia,Indonesia,21-11-2023,MS
...,...,...,...,...,...,...,...,...,...,...,...,...
888099,888199,100,NaN,NaN,JOHN GOSS,NaN,6580,NaN,NaN,CANADA,01-01-1990,MS
888199,888299,100,NaN,NaN,CAMILLA MARTIN,NaN,5690,NaN,NaN,DENMARK,01-01-1990,WS
888299,888399,100,NaN,NaN,DIDIT SULUH PATRIA / . UWIN,NaN,4800,NaN,NaN,INDONESIA,01-01-1990,MD
888399,888499,100,NaN,NaN,KAREN S. BECKMAN / GILLIAN M GOODWIN (GILKS),NaN,4800,NaN,NaN,ENGLAND,01-01-1990,WD
888499,888599,100,NaN,NaN,LEE KWANG JIN / GIL YOUNG AH,NaN,4880,NaN,NaN,KOREA,01-01-1990,XD

In [12]:
#in the above column we are able to print the entire row, column names whose rank is max, but now we just wanna display the country's name whose rank is maximum
df['country'][df["rank"]==df["rank"].max()]
df[['country','name']][df["rank"]==df["rank"].max()]

               country                                          name
99      Chinese Taipei                                  KUO KUAN LIN
199     Chinese Taipei                                   WANG PO-WEI
299            Austria                     COLLINS VALENTINE FILIMON
399            Vietnam                               NGUYEN HAI DANG
499          Indonesia                             CHRISTIAN ADINATA
...                ...                                           ...
888099          CANADA                                     JOHN GOSS
888199         DENMARK                                CAMILLA MARTIN
888299       INDONESIA                   DIDIT SULUH PATRIA / . UWIN
888399         ENGLAND  KAREN S. BECKMAN / GILLIAN M GOODWIN (GILKS)
888499           KOREA                  LEE KWANG JIN / GIL YOUNG AH

[8885 rows x 2 columns]

In [10]:
#in general index or sno are integers , but if we want to set index as per us then 
df.index
#when we run .set_index('column name') then a new data frame is created , not modifications in old data frame 
df.set_index('id')
#when we run .set_index('column name') then a new data frame is created , not modifications in old data frame , so when u want to not create a new data frame , modify the old data frame itself then do as
df.set_index('id',inplace=True)
df.columns.tolist()
#for col in df.columns:
 #   print(repr(col))
#once we changed the index values, we wanna reset the values then 
df.reset_index(inplace=True)
#this will list all the columns present in dataframe
df.columns

KeyError: "None of ['id'] are in the columns"

In [6]:
#if you wanna acess a particular row based on value then "df.loc[pass only index value']
df.index
df.loc[5]

Unnamed: 0                            5
rank                                  6
delta_rank                          1.0
country_code                        INA
name                   JONATAN CHRISTIE
id                                73442
points                            76921
tournaments_played                 18.0
continent                          Asia
country                       Indonesia
date                         24-10-2023
draw                                 MS
Name: 5, dtype: object

In [ ]:
#