In [1]:
import pandas as pd
df=pd.read_csv("ab.csv")
df

        date   open   high   low  close  volume
0  01-01-2001    180    987 -369      1     1.2
1  02-02-2002    190    654 -963      2     2.3
2  03-03-2003    150    321 -753     32     4.5
3  04-04-2004    123   -456 -159     55     5.6
4  05-05-2005    456   -258  168     69     6.7
5  06-06-2006    789   -147  752     85     7.8

In [3]:
# Step 1: Read the original CSV file
df = pd.read_csv("ab.csv")
# Step 2: Drop the column you want to skip (example: 'Age')
new_df = df.drop(columns=['date '])
# Step 3: Save the new DataFrame to a new CSV file
new_df.to_csv("new_file.csv", index=False)
new_df

   open   high   low  close  volume
0    180    987 -369      1     1.2
1    190    654 -963      2     2.3
2    150    321 -753     32     4.5
3    123   -456 -159     55     5.6
4    456   -258  168     69     6.7
5    789   -147  752     85     7.8

In [12]:
#now in new_df we can see that we don't have date column , so to include it what we can do is:
rng=pd.date_range(start="6/1/2025",end="6/5/2025",freq="B")
rng
#here B means business days without including weekends

DatetimeIndex(['2025-06-02', '2025-06-03', '2025-06-04', '2025-06-05'], dtype='datetime64[ns]', freq='B')

In [14]:
#now we have date range in rng, now we need to include the rng as index in new_df, and if we don't mention inplace=True, then the changes we set are applied in new newdataframe , if we mention then the changes are applied on original dataframe
#new_df.set_index(rng,inplace=True)
#new_df
#the below error raises bcz there are 6 rows in new_df , but we are generating dates of range from 1st june to 5th june that too only business days, so we are unable to keep the indices , so what we can do is 
#option1
rng = pd.date_range(start="6/1/2025", periods=len(new_df), freq="D")
new_df.set_index(rng, inplace=True)
new_df

#option2:
#Trim your DataFrame
#If you really want to keep only those 4 business days:

new_df = new_df.head(len(rng))
new_df.set_index(rng, inplace=True)

            open   high   low  close  volume
2025-06-01    180    987 -369      1     1.2
2025-06-02    190    654 -963      2     2.3
2025-06-03    150    321 -753     32     4.5
2025-06-04    123   -456 -159     55     5.6
2025-06-05    456   -258  168     69     6.7
2025-06-06    789   -147  752     85     7.8

In [ ]:
#In pd.date_range(), the parameter freq controls how the dates are spaced — basically, what kind of interval is used between each date.
#🔹 freq="D"
#"D" stands for calendar day frequency.
#It means every single day (including weekends).
#Example:
#pd.date_range(start="2025-06-01", periods=5, freq="D")
#Output:
#DatetimeIndex(['2025-06-01', '2025-06-02', '2025-06-03', '2025-06-04', '2025-06-05'], dtype='datetime64[ns]', freq='D')
#🔸 Some other common frequencies:
#freq	Meaning	Example result
#"D"	Daily (includes weekends)	2025-06-01, 2025-06-02, 2025-06-03
#"B"	Business days only (Mon–Fri)	2025-06-02, 2025-06-03, 2025-06-04
#"W"	Weekly (Sunday by default)	2025-06-01, 2025-06-08, 2025-06-15
#"ME"	Month end	2025-06-30, 2025-07-31
#"MS"	Month start	2025-06-01, 2025-07-01
#"H"	Hourly	2025-06-01 00:00, 2025-06-01 01:00, ...
#"T" or "min"	Minutes	2025-06-01 00:00, 2025-06-01 00:01, ...
#"S"	Seconds	2025-06-01 00:00:00, 2025-06-01 00:00:01, ...
#So in your case:
#rng = pd.date_range(start="6/1/2025", periods=len(new_df), freq="D")
#creates consecutive daily dates — perfect when your data represents rows for every day.
#Would you like me to show how to use "W", "M", or "B" visually with plots so you can see how each frequency affects data grouping?

In [19]:
%matplotlib inline
new_df["close"].plot()

In [ ]:
#Let’s go step by step to make sure you see the plot properly inside Jupyter Notebook.
#✅ Step-by-step in Jupyter Notebook
#1️⃣ Make sure inline plotting is enabled
#At the top of your notebook, run:
#%matplotlib inline
#This tells Jupyter to display plots inside the notebook, below the cell.
#2️⃣ Import required libraries (if not already done)
#import pandas as pd
#import matplotlib.pyplot as plt
#3️⃣ Plot your data
#If your DataFrame is named new_df and has a column called Close:
#new_df["Close"].plot()
#That’s it — your plot will appear right below the cell 🎯
#4️⃣ (Optional) Customize your plot
#new_df["Close"].plot(title="Stock Close Prices", xlabel="Date", ylabel="Price", grid=True)
#⚠️ If the plot still doesn’t appear
#Try these checks:
#Restart your kernel → sometimes Jupyter disables inline plotting after errors.
#Go to: Kernel > Restart Kernel
#Re-run:
#%matplotlib inline
#Then plot again.

In [21]:
new_df["2025-06-1":"2025-06-05"].close.mean()

np.float64(31.8)

In [23]:
#now this generates the dataframe with all dates , if our original dataframe has only business days , but now in dataframe u want to include all days , so as to fill the weekend days data what we do is we fill the data with the above rows data , this feature is possible bcz of method padding
new_df.asfreq('D',method='pad')
new_df.asfreq('h',method='pad')

                     open   high   low  close  volume
2025-06-01 00:00:00    180    987 -369      1     1.2
2025-06-01 01:00:00    180    987 -369      1     1.2
2025-06-01 02:00:00    180    987 -369      1     1.2
2025-06-01 03:00:00    180    987 -369      1     1.2
2025-06-01 04:00:00    180    987 -369      1     1.2
...                    ...    ...  ...    ...     ...
2025-06-05 20:00:00    456   -258  168     69     6.7
2025-06-05 21:00:00    456   -258  168     69     6.7
2025-06-05 22:00:00    456   -258  168     69     6.7
2025-06-05 23:00:00    456   -258  168     69     6.7
2025-06-06 00:00:00    789   -147  752     85     7.8

[121 rows x 5 columns]

In [24]:
#now sometimes we only know the start date to generate the data and we need to generate some 27 days date with business dates then we can use "periods"
range=pd.date_range(start="1/1/2025",periods=27,freq='B')
range

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10',
               '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
               '2025-01-17', '2025-01-20', '2025-01-21', '2025-01-22',
               '2025-01-23', '2025-01-24', '2025-01-27', '2025-01-28',
               '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-03',
               '2025-02-04', '2025-02-05', '2025-02-06'],
              dtype='datetime64[ns]', freq='B')

In [26]:
import numpy as np
np.random.randint(1,10,len(range))
ts=pd.Series(np.random.randint(1,10,len(range)),index=range)
ts

2025-01-01    9
2025-01-02    6
2025-01-03    6
2025-01-06    8
2025-01-07    5
2025-01-08    8
2025-01-09    2
2025-01-10    4
2025-01-13    3
2025-01-14    3
2025-01-15    5
2025-01-16    8
2025-01-17    3
2025-01-20    8
2025-01-21    6
2025-01-22    1
2025-01-23    3
2025-01-24    2
2025-01-27    9
2025-01-28    2
2025-01-29    9
2025-01-30    5
2025-01-31    8
2025-02-03    7
2025-02-04    2
2025-02-05    9
2025-02-06    5
Freq: B, dtype: int32