In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv("wind.csv")
df

          Date  temparature  windspeed rain
0   01-01-2003         10.0    -9999.0    n
1   02-02-2003         13.0        NaN    n
2   07-03-2003         15.0        NaN    n
3   27.03.2003         15.0        NaN    n
4     6.4.2003          NaN        NaN  NaN
5    11.6.2014          NaN        NaN  NaN
6     4.6.2003         27.0        NaN    y
7    13.3.2019          NaN        NaN  NaN
8     5.8.2003         27.0        NaN    y
9    29.9.2003          NaN   -88888.0  NaN
10  23.10.2003          NaN        NaN  NaN
11  17.11.2005          NaN        NaN  NaN
12  19.12.2003         15.0        NaN  NaN
13    3.9.2003          NaN   -77777.0  NaN
14   22.8.2003          NaN        NaN  NaN

In [10]:
#replace() takes 2 parameters , one is the parameter to be relased, the parameter replacing the old value this replacement works on entire table columns
nf=df.replace(-9999,np.nan)
nf
nf=df.replace([-9999,-88888,-77777],np.nan)
nf
#sometimes we need to replace nan values of only some columns not every column which has nan then this is how it works
nf=df.replace({'temparature':'Nan','windspeed':'Nan','rain':'n'},0)
nf
#You wrote 'Nan' (a string) — but in your DataFrame, the missing values are actually np.nan (the special NumPy "Not a Number" object), not the text 'Nan'.
#➡️ So pandas doesn’t find any actual 'Nan' strings to replace.
#💡 Why this works
#np.nan represents missing values (not a text).
#'Nan' is just a normal string.
#When your column actually contains true NaN values (from reading Excel/CSV), you must use np.nan to target them
nf = df.replace({'temparature': np.nan, 'windspeed': np.nan, 'rain': 'n'}, 0)
nf

          Date  temparature  windspeed rain
0   01-01-2003         10.0    -9999.0    0
1   02-02-2003         13.0        0.0    0
2   07-03-2003         15.0        0.0    0
3   27.03.2003         15.0        0.0    0
4     6.4.2003          0.0        0.0  NaN
5    11.6.2014          0.0        0.0  NaN
6     4.6.2003         27.0        0.0    y
7    13.3.2019          0.0        0.0  NaN
8     5.8.2003         27.0        0.0    y
9    29.9.2003          0.0   -88888.0  NaN
10  23.10.2003          0.0        0.0  NaN
11  17.11.2005          0.0        0.0  NaN
12  19.12.2003         15.0        0.0  NaN
13    3.9.2003          0.0   -77777.0  NaN
14   22.8.2003          0.0        0.0  NaN

In [11]:
nf=df.replace({-99999:np.nan,np.nan:'yy'})
nf
#This applies replacements globally (to the whole DataFrame) and not column-wise.
#Also, np.nan can’t be used as a key directly in a replace() dictionary — pandas can’t detect NaNs as keys because np.nan != np.nan.

          Date temparature windspeed rain
0   01-01-2003        10.0   -9999.0    n
1   02-02-2003        13.0        yy    n
2   07-03-2003        15.0        yy    n
3   27.03.2003        15.0        yy    n
4     6.4.2003          yy        yy   yy
5    11.6.2014          yy        yy   yy
6     4.6.2003        27.0        yy    y
7    13.3.2019          yy        yy   yy
8     5.8.2003        27.0        yy    y
9    29.9.2003          yy  -88888.0   yy
10  23.10.2003          yy        yy   yy
11  17.11.2005          yy        yy   yy
12  19.12.2003        15.0        yy   yy
13    3.9.2003          yy  -77777.0   yy
14   22.8.2003          yy        yy   yy

In [13]:
nf = df.replace({
    'windspeed': {-9999: np.nan},
    'rain': {np.nan: 'yy'}
})
nf
#'windspeed': {-99999: np.nan} → only replaces -99999 in the windspeed column with NaN.
#'rain': {np.nan: 'yy'} → only replaces missing values in the rain column with 'yy'.

          Date  temparature  windspeed rain
0   01-01-2003         10.0        NaN    n
1   02-02-2003         13.0        NaN    n
2   07-03-2003         15.0        NaN    n
3   27.03.2003         15.0        NaN    n
4     6.4.2003          NaN        NaN   yy
5    11.6.2014          NaN        NaN   yy
6     4.6.2003         27.0        NaN    y
7    13.3.2019          NaN        NaN   yy
8     5.8.2003         27.0        NaN    y
9    29.9.2003          NaN   -88888.0   yy
10  23.10.2003          NaN        NaN   yy
11  17.11.2005          NaN        NaN   yy
12  19.12.2003         15.0        NaN   yy
13    3.9.2003          NaN   -77777.0   yy
14   22.8.2003          NaN        NaN   yy

In [15]:
#Since NaN can’t be matched directly in a dictionary, a more reliable way is to use fillna() for the rain column:
df['windspeed'] = df['windspeed'].replace(-99999, np.nan)
df['rain'] = df['rain'].fillna('yy')
nf = df
nf

          Date  temparature  windspeed rain
0   01-01-2003         10.0    -9999.0    n
1   02-02-2003         13.0        NaN    n
2   07-03-2003         15.0        NaN    n
3   27.03.2003         15.0        NaN    n
4     6.4.2003          NaN        NaN   yy
5    11.6.2014          NaN        NaN   yy
6     4.6.2003         27.0        NaN    y
7    13.3.2019          NaN        NaN   yy
8     5.8.2003         27.0        NaN    y
9    29.9.2003          NaN   -88888.0   yy
10  23.10.2003          NaN        NaN   yy
11  17.11.2005          NaN        NaN   yy
12  19.12.2003         15.0        NaN   yy
13    3.9.2003          NaN   -77777.0   yy
14   22.8.2003          NaN        NaN   yy

In [16]:
#✅ Summary of both methods
#Method	Works for	Recommended
#replace({...})	Numeric replacements	✅ Good for -99999 → NaN
#fillna()	Missing value replacements	✅ Best for NaN → 'yy'
#So the clean final version would be:
df['windspeed'] = df['windspeed'].replace(-99999, np.nan)
df['rain'] = df['rain'].fillna('yy')
nf = df
nf

          Date  temparature  windspeed rain
0   01-01-2003         10.0    -9999.0    n
1   02-02-2003         13.0        NaN    n
2   07-03-2003         15.0        NaN    n
3   27.03.2003         15.0        NaN    n
4     6.4.2003          NaN        NaN   yy
5    11.6.2014          NaN        NaN   yy
6     4.6.2003         27.0        NaN    y
7    13.3.2019          NaN        NaN   yy
8     5.8.2003         27.0        NaN    y
9    29.9.2003          NaN   -88888.0   yy
10  23.10.2003          NaN        NaN   yy
11  17.11.2005          NaN        NaN   yy
12  19.12.2003         15.0        NaN   yy
13    3.9.2003          NaN   -77777.0   yy
14   22.8.2003          NaN        NaN   yy

In [19]:
#sometimes we need to replace the letters beside numbers with "" so as to do it we can take the help of regex
nf=df.replace('[A-Za-z]','',regex=True)
nf 
#the above one replaces globally columns whichever have alphabets in it , except nan ones 
#but sometimes we need to replace the alphabets only in specific columns not in every column this is how we do it
nf=df.replace({'temparature':'[A-Za-z]','windspeed':'[A-Za-z]'},'',regex=True)
nf

          Date  temparature  windspeed rain
0   01-01-2003         10.0    -9999.0    n
1   02-02-2003         13.0        NaN    n
2   07-03-2003         15.0        NaN    n
3   27.03.2003         15.0        NaN    n
4     6.4.2003          NaN        NaN   yy
5    11.6.2014          NaN        NaN   yy
6     4.6.2003         27.0        NaN    y
7    13.3.2019          NaN        NaN   yy
8     5.8.2003         27.0        NaN    y
9    29.9.2003          NaN   -88888.0   yy
10  23.10.2003          NaN        NaN   yy
11  17.11.2005          NaN        NaN   yy
12  19.12.2003         15.0        NaN   yy
13    3.9.2003          NaN   -77777.0   yy
14   22.8.2003          NaN        NaN   yy

In [22]:
#replacing one list with another list
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])
df

df = df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])
print(df)

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica

C:\Users\M Prabhakar\AppData\Local\Temp\ipykernel_25284\2674017131.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])
C:\Users\M Prabhakar\AppData\Local\Temp\ipykernel_25284\2674017131.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])