In [6]:
import pandas as pd
df=pd.read_csv(r"D:\UPSKILL 2025\Python Packages\bwf_historic_rankings.csv",low_memory=False)
df

,Unnamed: 0,rank,delta_rank,country_code,name,id,points,tournaments_played,continent,country,date,draw
0,0,1,0.0,DEN,VIKTOR AXELSEN,25831,107455,15.0,Europe,Denmark,24-10-2023,MS
1,1,2,0.0,INA,ANTHONY SINISUKA GINTING,95661,86611,19.0,Asia,Indonesia,24-10-2023,MS
2,2,3,0.0,JPN,KODAI NARAOKA,62063,82015,23.0,Asia,Japan,24-10-2023,MS
3,3,4,1.0,THA,KUNLAVUT VITIDSARN,64032,79778,18.0,Asia,Thailand,24-10-2023,MS
4,4,5,1.0,CHN,LI SHI FENG,95476,78548,23.0,Asia,China,24-10-2023,MS
...,...,...,...,...,...,...,...,...,...,...,...,...
888495,888595,96,NaN,NaN,MILES N C JOHNSON / SUZANNE LOUIS-LANE,NaN,4920,NaN,NaN,ENGLAND,01-01-1990,XD
888496,888596,97,NaN,NaN,PETER ROBERTS / LISA CAMPBELL,NaN,4900,NaN,NaN,AUSTRALIA,01-01-1990,XD
888497,888597,98,NaN,NaN,ZHANG QIANG / SHI WEN,NaN,4900,NaN,NaN,CHINA,01-01-1990,XD
888498,888598,99,NaN,NaN,PETER BLACKBURN / GILLIAN SANDERSON,NaN,4900,NaN,NaN,AUSTRALIA,01-01-1990,XD
888499,888599,100,NaN,NaN,LEE KWANG JIN / GIL YOUNG AH,NaN,4880,NaN,NaN,KOREA,01-01-1990,XD

In [7]:
#this gives us the max points 
df['points'].max()

122606

In [8]:
#return the dates when the matches are drawn:
df['date'][df['draw']=='MS']

0         24-10-2023
1         24-10-2023
2         24-10-2023
3         24-10-2023
4         24-10-2023
             ...
888095    01-01-1990
888096    01-01-1990
888097    01-01-1990
888098    01-01-1990
888099    01-01-1990
Name: date, Length: 177700, dtype: object

In [9]:
df['points'].mean()

np.float64(24801.090606640406)

In [ ]:
#the process of cleaning messy data is called data munging or data wrangling

In [10]:
#when we have nan in dataset its better to replace it with 0
df.fillna(0,inplace=True)
df

,Unnamed: 0,rank,delta_rank,country_code,name,id,points,tournaments_played,continent,country,date,draw
0,0,1,0.0,DEN,VIKTOR AXELSEN,25831,107455,15.0,Europe,Denmark,24-10-2023,MS
1,1,2,0.0,INA,ANTHONY SINISUKA GINTING,95661,86611,19.0,Asia,Indonesia,24-10-2023,MS
2,2,3,0.0,JPN,KODAI NARAOKA,62063,82015,23.0,Asia,Japan,24-10-2023,MS
3,3,4,1.0,THA,KUNLAVUT VITIDSARN,64032,79778,18.0,Asia,Thailand,24-10-2023,MS
4,4,5,1.0,CHN,LI SHI FENG,95476,78548,23.0,Asia,China,24-10-2023,MS
...,...,...,...,...,...,...,...,...,...,...,...,...
888495,888595,96,0.0,0,MILES N C JOHNSON / SUZANNE LOUIS-LANE,0,4920,0.0,0,ENGLAND,01-01-1990,XD
888496,888596,97,0.0,0,PETER ROBERTS / LISA CAMPBELL,0,4900,0.0,0,AUSTRALIA,01-01-1990,XD
888497,888597,98,0.0,0,ZHANG QIANG / SHI WEN,0,4900,0.0,0,CHINA,01-01-1990,XD
888498,888598,99,0.0,0,PETER BLACKBURN / GILLIAN SANDERSON,0,4900,0.0,0,AUSTRALIA,01-01-1990,XD
888499,888599,100,0.0,0,LEE KWANG JIN / GIL YOUNG AH,0,4880,0.0,0,KOREA,01-01-1990,XD