In [6]:
import pandas as pd
r={"city":["Darjeeling","Manali","Meghalaya"],
                 "ttt":[38,40,30],
                 }
s={"city":["Darjeeling","Manali","Meghalaya"],
                 "humidity":[10,11,9]}
rdf=pd.DataFrame(r)
sdf=pd.DataFrame(s)
rdf
sdf
df=pd.concat([rdf,sdf],axis=1)
df

         city  ttt        city  humidity
0  Darjeeling   38  Darjeeling        10
1      Manali   40      Manali        11
2   Meghalaya   30   Meghalaya         9

In [8]:
#we can merge 2 dataframes , when they have atleast one common column, it can be done using .merge(1st dataframe,2nd dataframe, on="mention common column name"):
dff=pd.merge(rdf,sdf,on="city")
dff

         city  ttt  humidity
0  Darjeeling   38        10
1      Manali   40        11
2   Meghalaya   30         9

In [10]:
#for eg let's consider that in 2dataframes we have the same column but with different values then if we merge them we only get the rows which are of having same column values from common column name
r={"city":["Darjeeling","Manali","Meghalaya","Mumbai"],
                 "ttt":[38,40,30,31],
                 }
s={"city":["Darjeeling","Manali","Meghalaya","Hyderabad"],
                 "humidity":[10,11,9,27]}
rdf=pd.DataFrame(r)
sdf=pd.DataFrame(s)
drs=pd.merge(rdf,sdf,on="city")
drs
#after printing drs we can see that its not giving us the details of unmatched rows from common column named city

         city  ttt  humidity
0  Darjeeling   38        10
1      Manali   40        11
2   Meghalaya   30         9

In [ ]:
#you can absolutely merge two DataFrames of unequal length in pandas.
#In fact, pd.merge() is specifically designed to handle that gracefully.
#💡 Key idea:
#When you merge two DataFrames, pandas aligns rows based on a common key column (like "city"), not on how many rows each DataFrame has.
#So the lengths don’t need to match at all.

🔹 Example 1 — Unequal lengths
import pandas as pd

# First dataframe (3 rows)
r = {"city": ["Darjeeling", "Manali", "Meghalaya"],
     "ttt": [38, 40, 30]}
rdf = pd.DataFrame(r)

# Second dataframe (only 2 rows)
s = {"city": ["Manali", "Darjeeling"],
     "humidity": [10, 11]}
sdf = pd.DataFrame(s)

# Merge on 'city'
df = pd.merge(rdf, sdf, on="city", how="outer")   # 'outer' keeps all rows
print(df)
Output:
        city  ttt  humidity
0  Darjeeling   38      11.0
1       Manali   40      10.0
2    Meghalaya   30       NaN


👉 Even though rdf has 3 rows and sdf has 2, the merge works fine.
NaN appears where there’s no matching value.

🔹 Merge types (important)
how	Keeps rows from	Missing data behavior
"inner"	Only common keys	Keeps only matching rows
"left"	Left DataFrame	Missing data filled with NaN
"right"	Right DataFrame	Missing data filled with NaN
"outer"	Both DataFrames	Keeps all rows from both sides

🔹 Example 2 — “Left” merge
If you want only rows from the first DataFrame:
df = pd.merge(rdf, sdf, on="city", how="left")
print(df)
Output:

        city  ttt  humidity
0  Darjeeling   38      11.0
1       Manali   40      10.0
2    Meghalaya   30       NaN


🔹 Example 3 — No matching column name?
You can also merge on different column names:
pd.merge(df1, df2, left_on="city_name", right_on="place")

✅ Summary

✔ You can merge DataFrames of different lengths.
✔ pandas aligns rows by matching key values, not by row count.
✔ Use how='outer' to keep all data from both DataFrames.

In [14]:
#how="outer" means it performs union between 2 dataframes and gives the merged op of 2dataframes
dss=pd.merge(rdf,sdf,on="city",how="outer")
dss
ds=pd.merge(rdf,sdf,on="city",how="inner")
ds
d=pd.merge(rdf,sdf,on="city",how="left")
d
df=pd.merge(rdf,sdf,on="city",how="right")
df
dff=pd.merge(rdf,sdf,on="city",how="right",indicator=True)
dff

         city   ttt  humidity      _merge
0  Darjeeling  38.0        10        both
1      Manali  40.0        11        both
2   Meghalaya  30.0         9        both
3   Hyderabad   NaN        27  right_only

In [17]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2
df3= pd.merge(df1,df2,on="city")
df3
df4= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df4

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,baltimore,38.0,75.0,NaN,NaN
1,chicago,14.0,68.0,21.0,65.0
2,new york,21.0,65.0,14.0,68.0
3,orlando,35.0,71.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0