In [6]:
import pandas as pd
#pivot allow us to transform or reshape the dataframe
df=pd.read_csv("weather.csv")
df

         DATE       CITY  TEMPARATURE  Humidity
0  01-01-2001  Hyderabad           27         5
1  01-02-2001  Hyderabad           28         5
2  01-03-2001  Hyderabad           29         5
3  01-04-2001  Hyderabad           30         5
4  01-05-2001  Hyderabad           25         5
5  01-06-2001     Mumbai           30        10
6  01-07-2001     Mumbai           31        10
7  01-08-2001     Mumbai           32        10
8  01-09-2001     Mumbai           33        10
9  01-10-2001     Mumbai           34        10

In [9]:
ddf=df.pivot(index="DATE",columns="CITY")
ddf

           TEMPARATURE         Humidity
CITY         Hyderabad Mumbai Hyderabad Mumbai
DATE
01-01-2001        27.0    NaN       5.0    NaN
01-02-2001        28.0    NaN       5.0    NaN
01-03-2001        29.0    NaN       5.0    NaN
01-04-2001        30.0    NaN       5.0    NaN
01-05-2001        25.0    NaN       5.0    NaN
01-06-2001         NaN   30.0       NaN   10.0
01-07-2001         NaN   31.0       NaN   10.0
01-08-2001         NaN   32.0       NaN   10.0
01-09-2001         NaN   33.0       NaN   10.0
01-10-2001         NaN   34.0       NaN   10.0

In [10]:
#pivot table is used to summarize and aggregate data inside dataframe
df=pd.read_csv("weather2.csv")
df

         DATE       CITY  TEMPARATURE  Humidity
0  01-01-2001  Hyderabad           27         5
1  01-01-2001  Hyderabad           28         5
2  01-01-2001  Hyderabad           29         5
3  01-04-2001  Hyderabad           30         5
4  01-04-2001  Hyderabad           25         5
5  01-04-2001     Mumbai           30        10
6  01-07-2001     Mumbai           31        10
7  01-07-2001     Mumbai           32        10
8  01-07-2001     Mumbai           33        10
9  01-09-2001     Mumbai           34        10

In [13]:
#now create a dataframe which shows avg temparature on a single day in cities
df.pivot_table(index="CITY",columns="DATE")

            Humidity                                  TEMPARATURE             \
DATE      01-01-2001 01-04-2001 01-07-2001 01-09-2001  01-01-2001 01-04-2001
CITY
Hyderabad        5.0        5.0        NaN        NaN        28.0       27.5
Mumbai           NaN       10.0       10.0       10.0         NaN       30.0


DATE      01-07-2001 01-09-2001
CITY
Hyderabad        NaN        NaN
Mumbai          32.0       34.0

In [14]:
df.pivot_table(index="CITY",columns="DATE",aggfunc="sum")

            Humidity                                  TEMPARATURE             \
DATE      01-01-2001 01-04-2001 01-07-2001 01-09-2001  01-01-2001 01-04-2001
CITY
Hyderabad       15.0       10.0        NaN        NaN        84.0       55.0
Mumbai           NaN       10.0       30.0       10.0         NaN       30.0


DATE      01-07-2001 01-09-2001
CITY
Hyderabad        NaN        NaN
Mumbai          96.0       34.0

In [15]:
df.pivot_table(index="CITY",columns="DATE",aggfunc="count")

            Humidity                                  TEMPARATURE             \
DATE      01-01-2001 01-04-2001 01-07-2001 01-09-2001  01-01-2001 01-04-2001
CITY
Hyderabad        3.0        2.0        NaN        NaN         3.0        2.0
Mumbai           NaN        1.0        3.0        1.0         NaN        1.0


DATE      01-07-2001 01-09-2001
CITY
Hyderabad        NaN        NaN
Mumbai           3.0        1.0

In [16]:
df.pivot_table(index="CITY",columns="DATE",aggfunc="diff")

   Humidity  TEMPARATURE
1       0.0          1.0
2       0.0          1.0
4       0.0         -5.0
7       0.0          1.0
8       0.0          1.0

In [18]:
df.pivot_table(index="CITY",columns="DATE",aggfunc="mean")

            Humidity                                  TEMPARATURE             \
DATE      01-01-2001 01-04-2001 01-07-2001 01-09-2001  01-01-2001 01-04-2001
CITY
Hyderabad        5.0        5.0        NaN        NaN        28.0       27.5
Mumbai           NaN       10.0       10.0       10.0         NaN       30.0


DATE      01-07-2001 01-09-2001
CITY
Hyderabad        NaN        NaN
Mumbai          32.0       34.0

In [19]:
df.pivot_table(index="CITY",columns="DATE",margins=True)

            Humidity                                        TEMPARATURE  \
DATE      01-01-2001 01-04-2001 01-07-2001 01-09-2001   All  01-01-2001
CITY
Hyderabad        5.0   5.000000        NaN        NaN   5.0        28.0
Mumbai           NaN  10.000000       10.0       10.0  10.0         NaN
All              5.0   6.666667       10.0       10.0   7.5        28.0


DATE      01-04-2001 01-07-2001 01-09-2001   All
CITY
Hyderabad  27.500000        NaN        NaN  27.8
Mumbai     30.000000       32.0       34.0  32.0
All        28.333333       32.0       34.0  29.9

In [25]:
df=pd.read_csv("weather3.csv")
df
#here in the date column the values are not in datetime datatype, they are in string format ,so to convert them to datetime format we can do as
df['DATE']=pd.to_datetime(df['DATE'])
df
type(df['DATE'])
#type(df['DATE'][0])

pandas.core.series.Series

In [23]:
#we have Grouper function in pandas
df.pivot_table(index=pd.Grouper(freq='M',key='DATE'),columns='CITY')

C:\Users\M Prabhakar\AppData\Local\Temp\ipykernel_12756\3493295541.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.pivot_table(index=pd.Grouper(freq='M',key='DATE'),columns='CITY')

            Humidity TEMPARATURE
CITY       Hyderabad   Hyderabad
DATE
2001-01-31       7.5        29.9