In [1]:
import pandas as pd
#melt is used to transform or reshape data
df=pd.read_csv("cities.csv")
df

         Day  Hyderabad  Kurnool  Anantapur  Mumbai  Delhi
0     Monday         15       30         30      30     40
1    Tuesday         16       31         31      29     39
2  Wednesday         17       32         32      28     38
3   Thursday         18       33         33      27     37
4     Friday         19       34         34      26     10
5   Saturday         20       35         35      25     15
6     Sunday         21       35         35      24     16

In [6]:
#.melt(dataframe name,id_vars=["columnname"])  
#id_vars=["columnname"]) is the column that u want to represent on x-axis
dd=pd.melt(df,id_vars=["Day"])
dd
#🔹 pd.melt() — What it does
#The melt() function in pandas is used to “unpivot” a DataFrame — that is, it converts data from a wide format to a long format.
#Think of it like turning columns into rows.
#🔹 Parameters explained
#df → your original DataFrame
#id_vars=["Day"] → columns that you want to keep as is (they will not be unpivoted)
#Other columns (not listed in id_vars) → are “melted” into two new columns:
#variable → the original column name
#value → the data from that column

#You use melt() when:
#You want to reshape data for easier plotting or analysis (e.g., with Seaborn or Matplotlib).
#You need a tidy format — where each column is a variable and each row is an observation
dd[dd["variable"]=="Hyderabad"]
#.#.melt(dataframe name,id_vars=["columnname"],var_name="new name of column",value_name="new name of another column") 
dd=pd.melt(df,id_vars=["Day"],var_name="city",value_name="temparatuer")
dd

          Day       city  temparatuer
0      Monday  Hyderabad           15
1     Tuesday  Hyderabad           16
2   Wednesday  Hyderabad           17
3    Thursday  Hyderabad           18
4      Friday  Hyderabad           19
5    Saturday  Hyderabad           20
6      Sunday  Hyderabad           21
7      Monday    Kurnool           30
8     Tuesday    Kurnool           31
9   Wednesday    Kurnool           32
10   Thursday    Kurnool           33
11     Friday    Kurnool           34
12   Saturday    Kurnool           35
13     Sunday    Kurnool           35
14     Monday  Anantapur           30
15    Tuesday  Anantapur           31
16  Wednesday  Anantapur           32
17   Thursday  Anantapur           33
18     Friday  Anantapur           34
19   Saturday  Anantapur           35
20     Sunday  Anantapur           35
21     Monday     Mumbai           30
22    Tuesday     Mumbai           29
23  Wednesday     Mumbai           28
24   Thursday     Mumbai           27
25     Friday     Mumbai           26
26   Saturday     Mumbai           25
27     Sunday     Mumbai           24
28     Monday      Delhi           40
29    Tuesday      Delhi           39
30  Wednesday      Delhi           38
31   Thursday      Delhi           37
32     Friday      Delhi           10
33   Saturday      Delhi           15
34     Sunday      Delhi           16